#pragma once

#include <fom-network/InteropTypes.h>

namespace FOMNetwork {
namespace Enum {

enum ItemSlotType : uint8_t {
  ITEM_SLOT_NONE = 0,

  WEAPON_SLOT_START = 1,
  ITEM_SLOT_WEAPON_1 = WEAPON_SLOT_START,
  ITEM_SLOT_WEAPON_2 = 2,
  ITEM_SLOT_WEAPON_3 = 3,
  WEAPON_SLOT_END = 4,
  NUM_WEAPON_SLOTS = WEAPON_SLOT_END - WEAPON_SLOT_START,

  EQUIPMENT_SLOT_START = 5,
  ITEM_SLOT_HEAD = EQUIPMENT_SLOT_START,
  ITEM_SLOT_EYES = 6,
  ITEM_SLOT_SHOULDERS = 7,
  ITEM_SLOT_TORSO = 8,
  ITEM_SLOT_ARMS = 9,
  ITEM_SLOT_HANDS = 10,
  ITEM_SLOT_LEGS = 11,
  ITEM_SLOT_BACK = 12,
  ITEM_SLOT_HAT = 13,
  ITEM_SLOT_SHIRT = 14,
  ITEM_SLOT_PANTS = 15,
  ITEM_SLOT_SHOES = 16,
  EQUIPMENT_SLOT_END = 17,
  NUM_EQUIPMENT_SLOTS = EQUIPMENT_SLOT_END - EQUIPMENT_SLOT_START,

  QUICKSLOT_START = 18,
  ITEM_SLOT_QUICKSLOT_1 = QUICKSLOT_START,
  ITEM_SLOT_QUICKSLOT_2 = 19,
  ITEM_SLOT_QUICKSLOT_3 = 20,
  ITEM_SLOT_QUICKSLOT_4 = 21,
  QUICKSLOT_END = 22,
  NUM_QUICKSLOTS = QUICKSLOT_END - QUICKSLOT_START,

  ITEM_SLOT_NANO_AUG = 26,

  ITEM_SLOT_MURDER_CARD = 52,
};

}  // namespace Enum
}  // namespace FOMNetwork
