#pragma once

#include <fom-network/InteropTypes.h>

namespace FOMNetwork {
namespace Enum {

enum ItemContainerType : uint8_t {
  ITEM_CONTAINER_NONE = 0,

  ITEM_CONTAINER_INVENTORY = 1,
  ITEM_CONTAINER_EQUIPMENT = 2,
  ITEM_CONTAINER_WEAPONS = 3,
  ITEM_CONTAINER_NANOMACHINE_AUGMENTATIONS = 4,
  ITEM_CONTAINER_QUICKSLOTS = 5,
  ITEM_CONTAINER_STORAGE = 6,
  ITEM_CONTAINER_ACTIVE_CONSUMABLES = 7,
  ITEM_CONTAINER_DESTROY = 8,

  ITEM_CONTAINER_LOOT = 11,

  ITEM_CONTAINER_TRANSPORT_STORAGE = 13,

  ITEM_CONTAINER_TRANSPORT_BUYBACK = 17,

  NUM_ITEM_CONTAINERS = 18
};

}  // namespace Enum
}  // namespace FOMNetwork
