#pragma once

#include <fom-network/Common.h>

namespace FOMNetwork {
namespace Enums {

enum PlayerAttribute : uint8_t {
  ATTRIBUTE_HEALTH = 0,
  ATTRIBUTE_STAMINA = 1,
  ATTRIBUTE_BIOENERGY = 2,
  ATTRIBUTE_AURA = 3,
  ATTRIBUTE_CREDITS = 4,
  ATTRIBUTE_FACTION_CREDITS = 5,
  ATTRIBUTE_EXPERIENCE_POINTS = 6,
  ATTRIBUTE_PENALTY_POINTS = 7,
  ATTRIBUTE_AVAILABLE_CLONES = 8,
  ATTRIBUTE_PRISONER = 9,
  ATTRIBUTE_FACTION_PRIVILEGES = 10,
  ATTRIBUTE_BOOSTER_1 = 11,
  ATTRIBUTE_BOOSTER_2 = 12,
  ATTRIBUTE_BOOSTER_3 = 13,
  ATTRIBUTE_SENATOR = 14,
  ATTRIBUTE_MOST_WANTED = 15,
  ATTRIBUTE_FUGITIVE = 16,
  ATTRIBUTE_AGILITY = 17,
  ATTRIBUTE_BALLISTIC_DAMAGE = 18,
  ATTRIBUTE_ENERGY_DAMAGE = 19,
  ATTRIBUTE_STAMINA_DAMAGE = 20,
  ATTRIBUTE_BIOENERGY_DAMAGE = 21,
  ATTRIBUTE_AURA_DAMAGE = 22,
  ATTRIBUTE_DESTRUCTION = 23,
  ATTRIBUTE_WEAPON_RECOIL = 24,
  ATTRIBUTE_ARMOR = 25,
  ATTRIBUTE_PROTECTION_REDUCTION = 26,
  ATTRIBUTE_SHIELDING = 27,
  ATTRIBUTE_ENDURANCE = 28,
  ATTRIBUTE_RESISTANCE = 29,
  ATTRIBUTE_REFLECTION = 30,
  ATTRIBUTE_DEFENSE_RATING = 31,
  ATTRIBUTE_BLOCK_RATING = 32,
  ATTRIBUTE_CRIT_RATING = 33,
  ATTRIBUTE_HEALTH_REGEN = 34,
  ATTRIBUTE_STAMINA_REGEN = 35,
  ATTRIBUTE_BIOENERGY_REGEN = 36,
  ATTRIBUTE_AURA_REGEN = 37,
  ATTRIBUTE_ADDICTION = 38,
  ATTRIBUTE_ADDICTION_TREATMENT = 39,
  ATTRIBUTE_COINS = 40,
  ATTRIBUTE_DRUG_COOLDOWN = 41,
  ATTRIBUTE_FOOD_COOLDOWN = 42,
  ATTRIBUTE_XENO_DAMAGE = 43,
  ATTRIBUTE_HEALTH_DRAIN = 44,
  ATTRIBUTE_STAMINA_DRAIN = 45,
  ATTRIBUTE_BIOENERGY_DRAIN = 46,
  ATTRIBUTE_AURA_LOSS = 47,
  ATTRIBUTE_MEDIKIT_COOLDOWN = 48,
  NUM_ATTRIBUTES = 49
};

}  // namespace Enums
}  // namespace FOMNetwork
