#pragma once

#include <fom-network/InteropTypes.h>

namespace FOMNetwork {
namespace Enum {

enum SkillType : uint32_t {
  SKILL_INVALID = 0,
  SKILL_BASIC_APPLICATION = 1,
  SKILL_STANDARD_PROCEDURES = 2,
  SKILL_ADVANCED_APPLICATION = 3,
  SKILL_EMERGENCY_MEDICATION = 4,
  SKILL_BIOLOGY = 5,
  // 6
  SKILL_NANOMACHINE_MEDICATION = 7,
  SKILL_PHYSICAL_EDUCATION = 8,
  SKILL_LIGHT_BALLISTIC_PROTECTION = 9,
  SKILL_HEAVY_BALLISTIC_PROTECTION = 10,
  SKILL_ALTERNATIVE_ARMOR_TECHNOLOGY = 11,
  SKILL_ARMOR_EFFICIENCY = 12,
  SKILL_WEIGHT_TRAINING = 13,
  SKILL_LIGHT_ENERGY_PROTECTION = 14,
  SKILL_HEAVY_ENERGY_PROTECTION = 15,
  SKILL_ENERGY_EFFICIENCY = 16,
  SKILL_PHYSICAL_ENHANCEMENT = 17,
  SKILL_DECRYPTION = 18,
  SKILL_INFILTRATION = 19,
  SKILL_INFLUENCE_MANIPULATION = 20,
  // 21
  SKILL_MECHANICAL_AUGMENTATION = 22,
  SKILL_NANOMACHINE_AUGMENTATION = 23,
  SKILL_GENETIC_RECONFIGURATION = 24,
  SKILL_BIOELECTRIC_EFFICIENCY = 25,
  // 26
  SKILL_ZANATHID_5_INFLEX = 27,
  SKILL_RYX_7_STREAMLINE = 28,
  SKILL_ARMALITE_SURVIVAL = 29,
  SKILL_TECHTRONIC_6X6 = 30,
  // 31
  // 32
  SKILL_RGI_9 = 33,
  SKILL_ORBIT_XB_INFINEON = 34,
  SKILL_ENFIELD_LIFE_PROTECTOR = 35,
  SKILL_FGZ_78 = 36,
  SKILL_MILITEK_EMP = 37,
  SKILL_HALLEM_TAR7 = 38,
  SKILL_CHRONO_ENERVON_EP24 = 39,
  SKILL_LINNER_PP7 = 40,
  SKILL_SALVOTEC_HP220 = 41,
  SKILL_EMP_RV3 = 42,
  SKILL_GAKK_MG6 = 43,
  SKILL_PROTONIX_BARRACUDA = 44,
  SKILL_AURELIAN_DOMINATOR = 45,
  SKILL_CRYOTECH_MEDIGUN_CM1 = 46,
  SKILL_FROSTBITE = 47,
  SKILL_HR420 = 48,
  SKILL_ENFIELD_ER_X = 49,
  SKILL_CRYOTECH_MEDIGUN_CM2 = 50,
  SKILL_EXPERIMENTAL_X01 = 51,
  SKILL_ZANATHID_55_COPKILLER = 52,
  SKILL_DOA_187 = 53,
  SKILL_HALLEM_IX78 = 54,
  SKILL_HAWK_72 = 55,
  SKILL_MINING_EQUIPMENT = 56,
  SKILL_MINERAL_SCANNERS = 57,
  SKILL_DRILLING_OPERATIONS = 58,
  // 59
  SKILL_CARBON_TECHNOLOGY = 60,
  SKILL_METAL_REFINEMENT = 61,
  SKILL_COMPRESSION = 62,
  SKILL_SILICON_TECHNOLOGY = 63,
  SKILL_SYNTACTIC_FOAM = 64,
  SKILL_ELECTRONICS = 65,
  SKILL_ADVANCED_ELECTRONICS = 66,
  SKILL_CARBON_ENHANCEMENT = 67,
  SKILL_BALLISTIC_AMMUNITION_PRODUCTION = 68,
  SKILL_ENERGY_AMMUNITION_PRODUCTION = 69,
  SKILL_ALIEN_TECHNOLOGY = 70,
  SKILL_ILLEGAL_REFINEMENT = 71,
  SKILL_FOOD_CREATION = 72,
  SKILL_ORGANIC_REFINEMENT = 73,
  SKILL_CHEMICAL_EDUCATION = 74,
  SKILL_CHEMICAL_MANIPULATION = 75,
  SKILL_BADGE_OF_VALOR = 76,
  SKILL_SHIELD_EXPERTISE = 77,
  SKILL_MOBILE_MEDICAL_STATION = 78,
  SKILL_BOUNTY_COLLECTION = 79,
  SKILL_ADVANCED_TRACKING = 80,
  SKILL_CONTRACTUAL_EFFICIENCY = 81,
  SKILL_LICENSE_TO_KILL = 82,
  SKILL_BALLISTIC_HANDGUN_PRODUCTION = 83,
  SKILL_BALLISTIC_RIFLE_PRODUCTION = 84,
  SKILL_KNIFE_PRODUCTION = 85,
  SKILL_SMG_PRODUCTION = 86,
  SKILL_LONG_RANGED_RIFLE_PRODUCTION = 87,
  SKILL_HANDHELD_EXPLOSIVE_PRODUCTION = 88,
  SKILL_ENERGY_PISTOL_PRODUCTION = 89,
  SKILL_TAZER_PRODUCTION = 90,
  SKILL_ENERGY_RIFLE_PRODUCTION = 91,
  SKILL_MEDICAL_ARMS_PRODUCTION = 92,
  SKILL_ALIEN_ARMS_PRODUCTION = 93,
  SKILL_ENERGY_LONGRIFLE_PRODUCTION = 94,
  SKILL_STANDARD_ARMOR_PRODUCTION = 95,
  SKILL_LIGHT_BALLISTIC_ARMOR_PRODUCTION = 96,
  SKILL_LIGHT_ENERGY_ARMOR_PRODUCTION = 97,
  SKILL_HEAVY_BALLISTIC_ARMOR_PRODUCTION = 98,
  SKILL_HEAVY_ENERGY_ARMOR_PRODUCTION = 99,
  // 100
  // 101
  // 102
  // 103
  SKILL_MEDIKIT_PRODUCTION = 104,
  SKILL_INJECTOR_PRODUCTION = 105,
  SKILL_MECHANICAL_AUGMENTATION_PRODUCTION = 106,
  SKILL_NANOMACHINE_AUGMENTATION_PRODUCTION = 107,
  SKILL_POSITIONING_SYSTEMS = 108,
  SKILL_DEPLOYABLE_PRODUCTION = 109,
  SKILL_BYPASS_HACKING_PRODUCTION = 110,
  SKILL_INFILTRATION_HACKING_PRODUCTION = 111,
  SKILL_BADGE_OF_DOMINANCE = 112,
  SKILL_DEPLOYABLE_EXPLOSIVES = 113,
  // 114
  // 115

  NUM_SKILL_TYPES = 116
};

}  // namespace Enum
}  // namespace FOMNetwork
