#pragma once

#include <fom-network/InteropTypes.h>

namespace FOMNetwork {
namespace Enum {

enum WorldObjectType : uint16_t {
  WORLD_OBJECT_TURRET = 501,
  WORLD_OBJECT_INTERACTIVE = 503,
  WORLD_OBJECT_COLONY_CONTROL = 505,
  WORLD_OBJECT_BACKPACK = 506,
  WORLD_OBJECT_ITEM = 507,
  WORLD_OBJECT_SERVICE = 508,
  WORLD_OBJECT_DEPLOYABLE = 509,
  WORLD_OBJECT_INFLUENCE_GENERATOR = 510,
  WORLD_OBJECT_MEDICAL_UNIT = 511,
  WORLD_OBJECT_MINING_RIG = 512,
  WORLD_OBJECT_SERVICE_CONTROL = 513,
  WORLD_OBJECT_NPC = 514,
  WORLD_OBJECT_TERRITORY_OBJECT = 515,
  WORLD_OBJECT_EXPLOSIVE_CHARGE = 516,
};

}  // namespace Enum
}  // namespace FOMNetwork
