#pragma once

#include <fom-network/InteropTypes.h>

namespace FOMNetwork {
namespace Enum {

enum WorldServiceType : uint8_t {
  WORLD_SERVICE_REPAIR_STATION = 1,
  WORLD_SERVICE_WORLD_MARKET = 2,
  WORLD_SERVICE_STORAGE_ACCESS = 3,
  WORLD_SERVICE_CHEMICAL_REFINERY = 4,
  WORLD_SERVICE_APARTMENT_ENTRY = 5,
  WORLD_SERVICE_PRISON_MANAGER = 6,
  WORLD_SERVICE_MEDICAL_UNIT = 7,
  WORLD_SERVICE_PRODUCTION = 8,
  WORLD_SERVICE_SCHEMATIC_MARKET = 9,
  // 10
  WORLD_SERVICE_ITEM_RECYCLER = 11,
  WORLD_SERVICE_VORTEX_TERMINAL = 12,
  // 13
  WORLD_SERVICE_STANDARD_MARKET = 14,
  WORLD_SERVICE_CLOTHING_MARKET = 15,
};

}  // namespace Enum
}  // namespace FOMNetwork
