name: PR Housekeeping

on:
  pull_request_target:

jobs:
  label:
    name: Apply Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Apply Project Labels
        uses: actions/labeler@v5
        with:
          sync-labels: true
